### ISSUE TITLE
subsequent-author-substitute ("———") wrongly appears inside bibliography item

### ISSUE THREAD

**Issue by njbart** [jgm/citeproc#10]
Relevant conditions: chapter item where author and editor are identical; chapter needs to appear in subsequent position, i.e., after at least one other item by the same author.

MWE:

```
pandoc -C -t plain <<EOT

Blah [@doe1; @doe2].

# References {-}

---
references:
- id: doe1
  type: book
  author:
  - family: Doe
    given: John
  issued:
    - year: 2020
  title: An anthology
- type: chapter
  id: doe2
  author:
    - family: Doe
      given: John
  container-title: An anthology
  editor:
    - family: Doe
      given: John
  issued:
    - year: 2020
  page: 63–79
  publisher: A publisher
  publisher-place: A place
  title: Some chapter  
...
EOT
```

Expected = output of pandoc’s current main branch:

```
Blah (Doe 2020a, 2020b).

References

Doe, John. 2020a. An Anthology.

———. 2020b. “Some Chapter.” In An Anthology, edited by John Doe, 63–79.
A place: A publisher.
```

Actual citeproc branch output:

```
Blah (Doe 2020a; 2020b).

References

Doe, John. 2020a. An Anthology.

———. 2020b. “Some Chapter.” In An Anthology, ———edited by, 63–79. A
place: A publisher.
```
