### ISSUE TITLE
Incorrect sorting of bibliography

### ISSUE THREAD

**Issue by jpcirrus** [jgm/citeproc#126]
The bibliography items are not sorted correctly when using an author-date csl stylesheet and with two or more items having the same year but not the same date specificity:

```
pandoc --citeproc -t plain  << EOT
---
references:
  - id: americancollegeofsportsmedicine1975
    author:
      - family: American College of Sports Medicine
        given: ''
    citation-key: americancollegeofsportsmedicine1975
    issued:
      - year: 1975
    title: Guidelines for graded exercise testing and exercise prescription
    type: book
  - id: americancollegeofsportsmedicine2013
    author:
      - family: American College of Sports Medicine
        given: ''
    citation-key: americancollegeofsportsmedicine2013
    issued:
      - year: 2013
    title: ACSM's resource manual for guidelines for exercise testing and prescription
    type: book
  - id: americancollegeofsportsmedicine2018
    author:
      - family: American College of Sports Medicine
        given: ''
    citation-key: americancollegeofsportsmedicine2018
    issued:
      - year: 2018
    title: ACSM's exercise testing and prescription
    type: book
  - id: americancollegeofsportsmedicine2021
    accessed:
      - year: 2021
        month: 12
        day: 15
    author:
      - family: American College of Sports Medicine
        given: ''
    citation-key: americancollegeofsportsmedicine2021
    issued:
      - year: 2021
        month: 11
        day: 10
    title: The American College of Sports Medicine
    type: webpage
    URL: https://bit.ly/3DSQHc8
  - id: americancollegeofsportsmedicine2021a
    author:
      - family: American College of Sports Medicine
        given: ''
    citation-key: americancollegeofsportsmedicine2021a
    issued:
      - year: 2021
    title: ACSM's guidelines for exercise testing and prescription
    type: book
nocite: |
  @*
...
EOT
```

Which ouputs:

```
American College of Sports Medicine. (2021a, November 10). The American College of Sports Medicine. https://bit.ly/3DSQHc8
American College of Sports Medicine. (1975). Guidelines for graded exercise testing and exercise prescription.
American College of Sports Medicine. (2013). ACSM’s resource manual for guidelines for exercise testing and prescription.
American College of Sports Medicine. (2018). ACSM’s exercise testing and prescription.
American College of Sports Medicine. (2021b). ACSM’s guidelines for exercise testing and prescription.
```

instead of the expected, and which is output directly in a Zotero bibliography export:

```
American College of Sports Medicine. (1975). Guidelines for graded exercise testing and exercise prescription.
American College of Sports Medicine. (2013). ACSM’s resource manual for guidelines for exercise testing and prescription.
American College of Sports Medicine. (2018). ACSM’s exercise testing and prescription.
American College of Sports Medicine. (2021a). ACSM’s guidelines for exercise testing and prescription.
American College of Sports Medicine. (2021b, November 10). The American College of Sports Medicine. https://bit.ly/3DSQHc8
```

As is seen: the two 2021 items are sorted incorrectly and with the wrong year suffixes. I think this could be the same issue that was reported in jgm/pandoc-citeproc#416 and fixed in pandoc 2.11.
