### ISSUE TITLE
Regression: DOIs with "https://doi.org/" prefix

### ISSUE THREAD

**Issue by njbart** [jgm/citeproc#15]
Many style guides, including the Chicago Manual, require DOIs in bibliographies to be shown with a `https://doi.org/` prefix. Unlike the "old" pandoc, the "new" pandoc from the "master" branch, source downloaded and self-compiled earlier today, outputs this prefix, but does not include it in the actual link. The DOI part itself is still clickable, but the appearance is weird, in particular if the DOI part but not the prefix is coloured and/or underlined.

MWE, including both a regular DOI and a [shortDOI](http://shortdoi.org/):

```
pandoc -C -t markdown-citations <<EOT

Blah [@doe1; @doe2].

# References {-}

---
references:
- id: doe1
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10/abcde
  issued:
    - year: 2020
  title: An article
- id: doe2
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10.1109/5.771073
  issued:
    - year: 2020
  title: Another article
...
EOT
```

Actual output:

```
Blah (Doe 2020a, 2020b).

References {#references .unnumbered}
==========

::: {#refs .references .csl-bib-body .hanging-indent}
::: {#ref-doe1 .csl-entry}
Doe, John. 2020a. "An Article."
https://doi.org/[10/abcde](https://doi.org/10/abcde).
:::

::: {#ref-doe2 .csl-entry}
---------. 2020b. "Another Article."
https://doi.org/[10.1109/5.771073](https://doi.org/10.1109/5.771073).
:::
:::
```

Expected output = output from the "old" pandoc:

```
Blah (Doe 2020a, 2020b).

References {#references .unnumbered}
==========

::: {#refs .references .hanging-indent}
::: {#ref-doe1}
Doe, John. 2020a. "An Article." <https://doi.org/10/abcde>.
:::

::: {#ref-doe2}
---------. 2020b. "Another Article." <https://doi.org/10.1109/5.771073>.
:::
:::
```

Same effect with latex and html output formats.

While we’re at it, something else that might be improved is one detail concerning the URL form of shortDOIs:

https://www.doi.org/resources.html states: ”The shortDOI Service is a public service for creating shortcuts to DOI names, which can be very long strings. The service creates short handles of the form 10/abcde and enables short HTTP URIs of the form http://doi.org/abcde that are ideal for use in email, blogs, mobile messaging and more.”

So the shortest URL form of a shortDOI is `https://doi.org/abcde` rather than `https://doi.org/10/abcde`. Would it be possible for pandoc to remove, only for shortDOIs, and only if the CSL style used requests the use of the URL form, the `10/` part?

(As to distinguishing regular DOIs and shortDOIs: shortDOIs invariably begin with `10/` whereas regular DOIs start with `10.`, see [here](https://www.doi.org/doi_handbook/2_Numbering.html).)
