### ISSUE TITLE
Regression: chicago-fullnote-bibliography.csl: First note is not "full"

### ISSUE THREAD

**Issue by njbart** [jgm/citeproc#16]
Formatting with chicago-fullnote-bibliography.csl, the first (foot-)note does not include the "full" details of the citation, just the short form.

Note that with a single citation per note this works as expected, but with two or more citations in a note, the "full" details are no longer rendered in the first note, as shown below. Subsequent notes include a year, too, which is unexpected as well.

```
pandoc -C -t markdown-citations <<EOT

Blah [@doe1; @doe2].

More blah [@doe1; @doe2].


# References {-}

---
csl: chicago-fullnote-bibliography.csl
references:
- id: doe1
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10/abcde
  issued:
    - year: 2020
  title: An article
- id: doe2
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10.1109/5.771073
  issued:
    - year: 2020
  title: Another article
...
EOT
```

Actual output:

```
Blah.[^1]

More blah.[^2]

References {#references .unnumbered}
==========

::: {#refs .references .csl-bib-body .hanging-indent}
::: {#ref-doe1 .csl-entry}
Doe, John. "An Article," 2020.
https://doi.org/[10/abcde](https://doi.org/10/abcde).
:::

::: {#ref-doe2 .csl-entry}
---------. "Another Article," 2020.
https://doi.org/[10.1109/5.771073](https://doi.org/10.1109/5.771073).
:::
:::

[^1]: Doe, "An Article," 2020; Doe, "Another Article," 2020.

[^2]: Doe, "An Article," 2020; Doe, "Another Article," 2020.
```

Expected = "old" pandoc (using `pandoc -F pandoc-citeproc -t markdown-citations`):

```
Blah.[^1]

More blah.[^2]

References {#references .unnumbered}
==========

::: {#refs .references .hanging-indent}
::: {#ref-doe1}
Doe, John. "An Article," 2020. <https://doi.org/10/abcde>.
:::

::: {#ref-doe2}
---------. "Another Article," 2020. <https://doi.org/10.1109/5.771073>.
:::
:::

[^1]: John Doe, "An Article," 2020, <https://doi.org/10/abcde>; John
    Doe, "Another Article," 2020, <https://doi.org/10.1109/5.771073>.

[^2]: Doe, "An Article"; Doe, "Another Article."
```
