### ISSUE TITLE
Citations in parentheses have a period before the close parentheses

### ISSUE THREAD

**Issue by fiapps** [jgm/citeproc#20]
I find that when I have a citation in the text of a footnote, it is wrapped in parentheses (a good improvement over pandoc-citeproc), but there is a period before the closing parenthesis (like this.).

Test case (`test.md`) – see the [Zotero Style Repository](https://www.zotero.org/styles?q=salesi) for the CSL style used:
```
Lorem ipsum dolor sit amet^[Consectetur adipisicing elit: «sed do eiusmod tempor incididunt» [@doe_1989, 15].].

---
csl: universita-pontificia-salesiana.csl
suppress-bibliography: true
references:
- id: doe_1989
  author:
    - family: Doe
      given: John
  issued:
    - year: 1989
  publisher: ABC
  publisher-place: New York
  title: Tempor
  type: book
...
```

command: `pandoc test.md --citeproc -t markdown-citations`

result with pandoc 2.11.0.2:
```
Lorem ipsum dolor sit amet[^1].

[^1]: Consectetur adipisicing elit: «sed do eiusmod tempor incididunt»
    (J. [Doe]{.smallcaps}, *Tempor*, New York, ABC, 1989, 15.).
```
