### ISSUE TITLE
Disambiguation error

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#44]
I'm referring to [this discussion](https://groups.google.com/g/pandoc-discuss/c/A6opAZhLAGI) on the mailing list. After checking it looks like citeproc's interpretation of `disambiguate="true"` is not correct.

This here should show the issue:

```
--- 
title: Test
csl: chicago-note-bibliography.csl
references:
- type: book
  id: doe1
  author:
  - family: Doe
    given: John
  issued:
    date-parts:
    - - 2020
      - 12
      - 1
  title: 'A first book by John Doe'
- type: book
  id: doe2
  author:
  - family: Doe
    given: John
  issued:
    date-parts:
    - - 2021
      - 1
      - 1
  title: 'A second book by John Doe'
- type: book
  id: smith
  author:
  - family: Smith
    given: Jane
  issued:
    date-parts:
    - - 2021
      - 1
      - 1
  title: 'A first book by Jane Smith'
---

Test [@doe1]
Test [@doe2]
Test [@smith]
```

I'm converting with: `pandoc file.md -o file.html --citeproc`

Result is:
![grafik](https://user-images.githubusercontent.com/4668198/104455661-e7b17c00-55a7-11eb-923d-a8dfd4aa651e.png)
