### ISSUE TITLE
Bold formatting seems to break punctuation moving and merging

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#48]
I have the following example:

```
--- 
title: Test
csl: chicago-note-bibliography-always-short-with-label.csl
references:
- type: article-journal
  id: doe1
  author:
  - family: Doe
    given: John
  issued:
    date-parts:
    - - 2020
      - 12
      - 1
  title: 'A first article by John Doe'
- type: article-journal
  id: doe2
  author:
  - family: Doe
    given: John
  issued:
    date-parts:
    - - 2020
      - 12
      - 1
  title: 'A second article by John Doe?'
---

Test [@doe1]
Test [@doe2]
```

Style: [chicago-note-bibliography-always-short-with-label.zip](https://github.com/jgm/citeproc/files/5859137/chicago-note-bibliography-always-short-with-label.zip)

The resulting bibliography looks like this:

![grafik](https://user-images.githubusercontent.com/4668198/105558943-31b90100-5d10-11eb-9cb6-562bcb3c0e0e.png)

As you can see the punctuation stays outside the quotes, and they don't get merged. If I remove the `font-weight="bold"` on line 1387 everything behaves as expected. I don't know if that is on purpose, but bold formatting seems to prevent punctuation moving and merging.
