### ISSUE TITLE
Multiple bibliographies

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#5]
Now, with the new citeproc library being more tightly integrated into pandoc proper, would that open ways to new features like multiple bibliographies? I'm thinking of having one bibliography with primary sources, another with secondary sources; or, per-section bibliographies, etc.

**Comment by jgm** [comment]
We could think about this, though it's not a priority right now.
How would you determine which item goes into which bibliography?

**Comment by denismaier** [comment]
Yes. Certainly not a top priority at the moment. But it's a much requested feature.

How would that work? At a most basic level perhaps some filters to exclude/include items:

:::refs include:type=book
:::

These filters could also be defined in the metadata.

For per-section bibliographies you'll need  a mechanism to define the segments, or restart the bibliography at certain points.

**Comment by denismaier** [comment]
Defining bibliographies in the metadata could look like this:

```
bibliography-filters:
  - id: bibliographyA 
    exclude: 
      - type: book
  - id: bibliographyB
    include: 
      - type: book
```

In the document, you might call this with:

```
::: {#refs .bibliographyB}
:::
```

Or:

```
::: {#refs filtered=bibliographyB}
:::
```
