### ISSUE TITLE
Inner quotes handled incorrectly for it-IT locale.

### ISSUE THREAD

**Issue by fiapps** [jgm/citeproc#87]
In Italian, «» are used for outer quotes, and "" for inner quotes, and the [it-IT CSL locale](https://github.com/citation-style-language/locales/blob/master/locales-it-IT.xml) (lines 74–77) specifies this. When a pandoc citation has a quotation with inner and outer quotes in its suffix, the inner quotes are changed from "" to «» if the locale is `it-IT`, whether this is specified by pandoc `lang` metadata or a `default-locale="it-IT"` attribute on the `style` element in the CSL file.

I assume this is a bug in citeproc because it does not happen to quotations in body text.

Test file (`test-quotes.md`):
```
Foo[@a 50: «Disse: "bar"»]. «Disse: "baz"»

---
suppress-bibliography: true
references:
- id: a
  author:
    - literal: Aristotele
  title: Metafisica
  type: book
...
```

Correct output from `pandoc test-quotes.md --citeproc --csl universita-pontificia-salesiana.csl -t markdown-citations`:

```
Foo[^1]. «Disse: "baz"»

[^1]: [Aristotele]{.smallcaps}, *Metafisica*, 50: «Disse: "bar"».
```

Incorrect output from `pandoc test-quotes.md --citeproc --csl universita-pontificia-salesiana.csl -M lang=it-IT -t markdown-citations`:

```
Foo[^1]. «Disse: "baz"»

[^1]: [Aristotele]{.smallcaps}, *Metafisica*, 50: «Disse: «bar»».
```

`pandoc --version` reports:
```
pandoc 2.14.1
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.11,
citeproc 0.4.1, ipynb 0.1.0.1
```
