### ISSUE TITLE
Missing locator after collapsing and grouping

### ISSUE THREAD

**Issue by benjaminmoon** [jgm/citeproc#96]
With multiple citations by the same author in a group, if one contains a suffix the citation is not collapsed, or the locator might be lost.

As an example of what I want/expect:

> (Author 2021a, p. 1, b); (Author 2021a, b, p. 6); (Author 2021a, b, *et seq.*)

What I'm getting:

> (Author 2021a, p. 1, b); (Author 2021a, b); (Author 2021a; Author 2021b, *et seq.*)

I'm using the style file here: <https://github.com/citation-style-language/styles/blob/master/monographs-of-the-palaeontographical-society.csl>

The first citation above is correct, but the second loses the locator and the third (with a suffix) doesn't collapse the citations. I'm uncertain whether this is citeproc or some incorrect setup in the CSL style. Any help would be much appreciated.

I'm using pandoc v. 2.16.2 and citeproc 0.6 installed through homebrew on macOS 12.1.

Here's an example I've used to recreate the issue:

```
---
references:
- id: Author2021EJ
  author:
    - family: Author
      given: A. A.
  container-title: The Journal
  issued:
    - year: 2021
      month: 1
  page: 1–5
  title: Article 1
  type: article-journal
  volume: '1'

- id: Author2021EJa
  author:
    - family: Author
      given: A. A.
  container-title: The Journal
  issue: '1'
  issued:
    - year: 2021
      month: 2
  page: 6–10
  title: Article 2
  type: article-journal
  volume: '1'

csl: https://raw.githubusercontent.com/citation-style-language/styles/master/monographs-of-the-palaeontographical-society.csl
---

# This collapses correctly

[@Author2021EJ, p. 1; @Author2021EJa]

# This doesn't show locator for second citation

[@Author2021EJ; @Author2021EJa, p. 6]

# These don't collapse at all

[@Author2021EJ, *et seq.*; @Author2021EJa]
[@Author2021EJ; @Author2021EJa, *et seq.*]
```

**Comment by jgm** [comment]
Collapsing implies grouping.
Grouping can cause problems when there are prefixes and suffixes, because it can reorder citations.  Hence we are conservative about doing it in these cases.
The missing locator, though, is definitely a bug.

**Comment by benjaminmoon** [comment]
Okay that makes sense; I think fortunately it's rare enough that I can manually edit the output (or leave it be).

Thanks for your help.

**Comment by jgm** [comment]
Slightly smaller test case for the disappearing locator:
```
---
references:
- id: aa
  author:
    - family: Author
      given: A. A.
  container-title: The Journal
  issued:
    - year: 2021
  page: 1–5
  title: Article 1
  type: article-journal
  volume: '1'

- id: bb
  author:
    - family: Author
      given: A. A.
  container-title: The Journal
  issued:
    - year: 2021
  page: 6–10
  title: Article 2
  type: article-journal
  volume: '1'
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/monographs-of-the-palaeontographical-society.csl
---

# This doesn't show locator for second citation

[@aa, p. 100; @bb, p. 6]

# By itself is fine

[@bb, p. 6]

```
